# Generated by Django 5.2.11 on 2026-02-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_thumb',
            field=models.ImageField(blank=True, upload_to='banners/thumbs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo_thumb',
            field=models.ImageField(blank=True, upload_to='products/thumbs/'),
        ),
    ]
